#!/bin/sh

ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
LAMBDA_FILES=$(find $(git rev-parse --show-toplevel)/LambdaFunctions | grep .js$)

if [[ "$LAMBDA_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nValidating Lambdas:\n"


if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm --dev install) \n"
  exit 1
fi

for FILE in $LAMBDA_FILES
do
  "$ESLINT" "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t\033[32mESLint Passed: $FILE\033[0m \n"
  else
    printf "\t\033[41mESLint Failed: $FILE\033[0m \n"
    PASS=false
  fi
done

printf "Lambda validation completed.\n"

if ! $PASS; then
  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
